PULSE-211 add patient name info
pulse-admin/data-model pull request #14
Opened 2016-10-19 14:01 UTC by brianlindsy

2016-10-19 16:41 UTC, kekey1 commented on data-model.sql
>  	alternate_care_facility_id bigint,
should address_id be removed at this point? i know it will be removed shortly, just not sure why it is related to the name change.

2016-10-19 17:06 UTC, kekey1 commented on data-model.sql
> +CREATE TABLE name_type (
These "lookup" tables that have a finite set of known values should be filled in when the reset script is run. However, I already had to add a preload.sql file in the task I'm in the middle of working on so to avoid conflict maybe I can let you know what I'm finished with that and you can go back to add preload data for these tables at that time? No change here at this time.

2016-10-19 17:07 UTC, kekey1 requested changes
Left a couple comments - one thing does not require a change yet and the other I think should.

2016-10-19 17:20 UTC, brianlindsy commented on data-model.sql
>  	alternate_care_facility_id bigint,
You're right, I was probably getting ahead of myself here.

2016-10-19 17:24 UTC, kekey1 approved these changes

2016-10-19 17:24 UTC, brianlindsy commented on data-model.sql
> +CREATE TABLE name_type (
Sounds good.

2016-10-19 21:16 UTC, kekey1 requested changes
one small thing!

2016-10-19 21:16 UTC, kekey1 commented on data-model.sql
> -	organization_patient_id varchar(1024) not null,
The "organization_patient_id" should actually still be there. It's meant to hold whatever ID the organization assigns to that patient. I think it's like an alphanumeric GUID that comes back in the SOAP response for patient discovery.

2016-10-21 14:18 UTC, kekey1 approved these changes

2016-10-21 14:20 UTC, merged