PULSE-266 add audit tables
pulse-admin/data-model pull request #26
Opened 2016-12-08 19:42 UTC by brianlindsy

2016-12-08 19:49 UTC, andlar requested changes
Some changes / questions in the review

2016-12-08 19:49 UTC, andlar commented on data-model.sql
> +	network_access_point_type_code varchar(1), --"1" for machine (DNS) name, "2" for IP address
If this is a code-based lookup, it probably should be a foreign-key relationship to a table of those codes

2016-12-08 19:49 UTC, andlar commented on data-model.sql
> +	network_access_point_type_code varchar(1), --"1" for machine (DNS) name, "2" for IP address
Same FK

2016-12-08 19:49 UTC, andlar commented on data-model.sql
> +	network_access_point_type_code varchar(1), --"1" for machine (DNS) name, "2" for IP address
Same FK

2016-12-08 19:49 UTC, andlar commented on data-model.sql
> +	participant_object_type_code smallint NOT NULL, -- "2" (System)
Should this one (and the next line) be lookup tables too?

2016-12-08 19:49 UTC, andlar commented on data-model.sql
> +	participant_object_query text, -- the QueryByParameter segment of the query, base64 encoded
I do like the comments you've included

2016-12-08 19:49 UTC, andlar commented on data-model.sql
> +	event_date_time varchar(100),
Assuming this isn't an actual date/time object? But instead some string representation of one?

2016-12-08 19:49 UTC, andlar commented on data-model.sql
> +CREATE TRIGGER audit_event_audit AFTER INSERT OR DELETE OR UPDATE ON audit_event FOR EACH ROW EXECUTE PROCEDURE audit.if_modified_func();
Can you double-check that each of the tables in the data-model have two triggers for them? It looks like audit_document was added, but I don't see audit_document_* triggers, and it'd be good to verify that the triggers are up to date

2016-12-08 20:06 UTC, kekey1 approved these changes
Nothing to add to Andrew's review

2016-12-08 20:17 UTC, brianlindsy commented on data-model.sql
> +	event_date_time varchar(100),
Yes, I'm inserting a string representation of a date into that field.

2016-12-08 20:22 UTC, brianlindsy commented on data-model.sql
> +	network_access_point_type_code varchar(1), --"1" for machine (DNS) name, "2" for IP address
I guess I could make a lookup table but it would only be two values "1" and "2".

2016-12-08 20:55 UTC, andlar commented on data-model.sql
> +	network_access_point_type_code varchar(1), --"1" for machine (DNS) name, "2" for IP address
I know it's annoying, but this _is_ a lookup item, so it _should_ be in a table. In the new table you add I'd do the insert something like: insert into table (code, description) values (1, "Machine (DNS) name"),(2, "IP Address")

That said, this is a tiny table; if @kekey1 is okay with not doing the lookup I can grit my teeth and accept it, but...

2016-12-08 20:59 UTC, brianlindsy commented on data-model.sql
> +	participant_object_type_code smallint NOT NULL, -- "2" (System)
This may actually be a lookup table with a buch of values but we would only be using two. I can change that

2016-12-08 21:00 UTC, brianlindsy commented on data-model.sql
> +	network_access_point_type_code varchar(1), --"1" for machine (DNS) name, "2" for IP address
Ill make a lookup table for it to make things look nice :)

2016-12-12 14:42 UTC, andlar approved these changes

2016-12-12 14:54 UTC, merged