PULSE-421 clear phi script
pulse-admin/data-model pull request #48
Opened 2017-04-13 13:54 UTC by brianlindsy

2017-04-13 14:07 UTC, kekey1 requested changes

2017-04-13 14:07 UTC, kekey1 commented on clear-phi.sh
> +psql -h localhost -U pulse -f clear-phi.sql pulse
Can you make this take command line arguments for the host and user? The reset.sh script does something similar.

2017-04-14 20:52 UTC, kekey1 approved these changes

2017-04-17 11:26 UTC, andlar approved these changes

2017-04-17 11:26 UTC, merged